src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <externalId>true</externalId>
        <label>Slack Team ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <externalId>true</externalId>
        <label>Slack User ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/SlackTeamId__c.field-meta.xml
<CustomField>
    <fullName>SlackTeamId__c</fullName>
    <formula>Account.SlackTeamId__c</formula>
    <label>Slack Team ID</label>
    <type>Text</type>
</CustomField>

src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelativeTestService.cls
/**
 * This class is used to create test or sample data that has relative dates
 * to a given reference date. The data would be useful for setting up data
 * to test commands that handle concepts like "yesterday" or "last week".
 */
public class RelativeTestService {

    private Datetime reference;
    private Date referenceDate;
    private Time referenceTime;
    private String timeZoneSidKey;

    public RelativeTestService(Datetime reference, String timeZoneSidKey) {
        this.reference = reference;
        this.timeZoneSidKey = timeZoneSidKey;

        this.referenceDate = DateTimeUtil.getDate(
                this.reference, timeZoneSidKey);
        this.referenceTime = DateTimeUtil.getTime(
                this.reference, timeZoneSidKey);
    }

    public static RelativeTestService getInstance(
            Datetime referenceDate, String timeZoneSidKey) {
        return new RelativeTestService(referenceDate, timeZoneSidKey);
    }

    public void setup() {

        // Create accounts
        Account board = new Account(
                Name = 'Board, Inc. (TEST)',
                SlackTeamId__c = 'board');

        insert new List<Account> {
            board
        };

        // Create contacts
        Contact flip = new Contact(
                AccountId = board.Id,
                FirstName = 'Baxter',
                LastName = 'Flip (TEST)',
                SlackUserId__c = 'flip');

        insert new List<Contact> {
            flip
        };

        // Create time entries

        TimeEntry__c flipboard30mAgo = new TimeEntry__c(
                StartTime__c = this.reference.addMinutes(-30),
                SlackUserId__c = 'flip',
                SlackTeamId__c = 'board');

        insert new List<TimeEntry__c> {
            flipboard30mAgo
        };
    }
}