src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <externalId>true</externalId>
        <label>Slack Team ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <externalId>true</externalId>
        <label>Slack User ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TimeZoneSidKey__c</fullName>
        <defaultValue>&apos;America/New_York&apos;</defaultValue>
        <description>Time zone in which the contact is located, used to determine cutoff dates for weekly time reports</description>
        <inlineHelpText>Time zone in which the contact is located, used to determine cutoff dates for weekly time reports</inlineHelpText>
        <label>Time Zone</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeZoneSidKey</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/SlackTeamId__c.field-meta.xml
<CustomField>
    <fullName>SlackTeamId__c</fullName>
    <formula>Account.SlackTeamId__c</formula>
    <label>Slack Team ID</label>
    <type>Text</type>
</CustomField>

src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/TimeZoneSidKey.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Africa/Algiers</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Cairo</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Casablanca</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Johannesburg</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Nairobi</fullName>
    </customValue>
    <customValue>
        <fullName>America/Adak</fullName>
    </customValue>
    <customValue>
        <fullName>America/Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>America/Argentina/Buenos_Aires</fullName>
    </customValue>
    <customValue>
        <fullName>America/Bogota</fullName>
    </customValue>
    <customValue>
        <fullName>America/Caracas</fullName>
    </customValue>
    <customValue>
        <fullName>America/Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Denver</fullName>
    </customValue>
    <customValue>
        <fullName>America/El_Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>America/Halifax</fullName>
    </customValue>
    <customValue>
        <fullName>America/Indiana/Indianapolis</fullName>
    </customValue>
    <customValue>
        <fullName>America/Lima</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mazatlan</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mexico_City</fullName>
    </customValue>
    <customValue>
        <fullName>America/New_York</fullName>
        <default>true</default>
        <label>America/New_York</label>
    </customValue>
    <customValue>
        <fullName>America/Panama</fullName>
    </customValue>
    <customValue>
        <fullName>America/Phoenix</fullName>
    </customValue>
    <customValue>
        <fullName>America/Puerto_Rico</fullName>
    </customValue>
    <customValue>
        <fullName>America/Santiago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Sao_Paulo</fullName>
    </customValue>
    <customValue>
        <fullName>America/Scoresbysund</fullName>
    </customValue>
    <customValue>
        <fullName>America/St_Johns</fullName>
    </customValue>
    <customValue>
        <fullName>America/Tijuana</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baghdad</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baku</fullName>
    </customValue>
    <customValue>
        <fullName>Europe/London</fullName>
    </customValue>
    <description>Time zone values matching what&apos;s stored by Salesforce on User records</description>
    <masterLabel>Time Zone</masterLabel>
</GlobalValueSet>

src/classes/SlashclockEntriesCommandTest.cls
@isTest
private class SlashclockEntriesCommandTest {

    @testSetup
    private static void setup() {
        RelativeTestService.getInstance(
                Datetime.now(), 'Europe/London').setup();
    }

    @isTest
    private static void clockEntriesAfterSlice30Minutes() {

        // Given
        Contact skate = [
            SELECT
                Account.SlackTeamId__c,
                AccountId,
                SlackUserId__c,
                TimeZoneSidKey__c,
                Id
            FROM Contact
            WHERE LastName = 'Skate (TEST)'
        ];

        Slashclock.Command givenCommand = new SlashclockEntriesCommand();
        
        givenCommand.load(
                new SlashCommand__c(
                        SlackUserId__c = skate.SlackUserId__c,
                        SlackTeamId__c = skate.Account.SlackTeamId__c,
                        Text__c = 'entries',
                        Command__c = '/clock'));

        Slashclock.CommandResult givenResult = givenCommand.execute();

        List<String> givenMessageParts = givenResult.getMessage().split('\n');

        System.assertEquals(
                'Here\'s what you\'ve clocked over the last seven days.',
                givenMessageParts.get(0),
                'givenMessageParts.get(0)');

        System.assert(
                givenMessageParts.get(1).endsWith('10:15am - 5:45pm'),
                givenMessageParts.get(1) + ' should end with ' + '10:15am - 5:45pm');

        System.assert(
                givenMessageParts.get(2).endsWith('9:15am - 9:45am'),
                givenMessageParts.get(2) + ' should end with ' + '9:15am - 9:45am');
    }
}