src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <externalId>true</externalId>
        <label>Slack Team ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <externalId>true</externalId>
        <label>Slack User ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TimeZoneSidKey__c</fullName>
        <defaultValue>&apos;America/New_York&apos;</defaultValue>
        <description>Time zone in which the contact is located, used to determine cutoff dates for weekly time reports</description>
        <inlineHelpText>Time zone in which the contact is located, used to determine cutoff dates for weekly time reports</inlineHelpText>
        <label>Time Zone</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>TimeZoneSidKey</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/SlackTeamId__c.field-meta.xml
<CustomField>
    <fullName>SlackTeamId__c</fullName>
    <formula>Account.SlackTeamId__c</formula>
    <label>Slack Team ID</label>
    <type>Text</type>
</CustomField>

src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>EndTIme__c</fullName>
        <label>End TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTimeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>StartTimeZoneSidKey__c</fullName>
    <description>The time zone in which the Start Time was entered</description>
    <inlineHelpText>The time zone in which the Start Time was entered</inlineHelpText>
    <label>Start Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZoneSidKey</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TimeZoneSidKey.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Africa/Algiers</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Cairo</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Casablanca</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Johannesburg</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Nairobi</fullName>
    </customValue>
    <customValue>
        <fullName>America/Adak</fullName>
    </customValue>
    <customValue>
        <fullName>America/Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>America/Argentina/Buenos_Aires</fullName>
    </customValue>
    <customValue>
        <fullName>America/Bogota</fullName>
    </customValue>
    <customValue>
        <fullName>America/Caracas</fullName>
    </customValue>
    <customValue>
        <fullName>America/Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Denver</fullName>
    </customValue>
    <customValue>
        <fullName>America/El_Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>America/Halifax</fullName>
    </customValue>
    <customValue>
        <fullName>America/Indiana/Indianapolis</fullName>
    </customValue>
    <customValue>
        <fullName>America/Lima</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mazatlan</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mexico_City</fullName>
    </customValue>
    <customValue>
        <fullName>America/New_York</fullName>
    </customValue>
    <customValue>
        <fullName>America/Panama</fullName>
    </customValue>
    <customValue>
        <fullName>America/Phoenix</fullName>
    </customValue>
    <customValue>
        <fullName>America/Puerto_Rico</fullName>
    </customValue>
    <customValue>
        <fullName>America/Santiago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Sao_Paulo</fullName>
    </customValue>
    <customValue>
        <fullName>America/Scoresbysund</fullName>
    </customValue>
    <customValue>
        <fullName>America/St_Johns</fullName>
    </customValue>
    <customValue>
        <fullName>America/Tijuana</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baghdad</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baku</fullName>
    </customValue>
    <description>Time zone values matching what&#39;s stored by Salesforce on User records</description>
    <masterLabel>Time Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RelativeTestService.cls
/**
 * This class is used to create test or sample data that has relative dates
 * to a given reference date. The data would be useful for setting up data
 * to test commands that handle concepts like "yesterday" or "last week".
 */
public class RelativeTestService {

    private Datetime reference;
    private Date referenceDate;
    private Time referenceTime;
    private String timeZoneSidKey;

    public RelativeTestService(Datetime reference, String timeZoneSidKey) {
        this.reference = reference;
        this.timeZoneSidKey = timeZoneSidKey;

        this.referenceDate = DateTimeUtil.getDate(
                this.reference, timeZoneSidKey);
        this.referenceTime = DateTimeUtil.getTime(
                this.reference, timeZoneSidKey);
    }

    public static RelativeTestService getInstance(
            Datetime referenceDate, String timeZoneSidKey) {
        return new RelativeTestService(referenceDate, timeZoneSidKey);
    }

    public void setup() {

        Datetime twoDaysAgo = this.reference.addDays(-2);
        Datetime oneDaysAgo = this.reference.addDays(-1);
        Datetime thirtyMinutesAgo = this.reference.addMinutes(-30);
        
        Date yesterday = this.referenceDate.addDays(-1);
        
        Datetime yesterdayNineFifteen =
                DateTimeUtil.newDatetime(
                        yesterday, Time.newInstance(9, 15, 0, 0),
                        this.timeZoneSidKey);
        
        Datetime yesterdayTenFifteen =
                DateTimeUtil.newDatetime(
                        yesterday, Time.newInstance(10, 15, 0, 0),
                        this.timeZoneSidKey);

        // Create accounts
        Account board = new Account(
                Name = 'Board, Inc. (TEST)',
                SlackTeamId__c = 'board');

        insert new List<Account> {
            board
        };

        // Create contacts
        Contact flip = new Contact(
                AccountId = board.Id,
                FirstName = 'Baxter',
                LastName = 'Flip (TEST)',
                SlackUserId__c = 'flip',
                TimeZoneSidKey__c = this.timeZoneSidKey);

        Contact kick = new Contact(
                AccountId = board.Id,
                FirstName = 'Dynamo',
                LastName = 'Kick (TEST)',
                SlackuserId__c = 'kick',
                TimeZoneSidKey__c = this.timeZoneSidKey);

        Contact skate = new Contact(
                AccountId = board.Id,
                FirstName = 'Slick',
                LastName = 'Skate (TEST)',
                SlackUserId__c = 'skate',
                TimeZoneSidKey__c = this.timeZoneSidKey);

        insert new List<Contact> {
            skate,
            kick,
            flip
        };

        // Create time entries
        TimeEntry__c kickboard2DaysAgo = new TimeEntry__c(
                Contact__c = kick.Id,
                StartTime__c = twoDaysAgo,
                StartTimeZoneSidKey__c = this.timeZoneSidKey,
                SlackUserId__c = 'kick',
                SlackTeamId__c = 'board');

        TimeEntry__c flipboard30mAgo = new TimeEntry__c(
                Contact__c = flip.Id,
                StartTime__c = thirtyMinutesAgo,
                SlackUserId__c = 'flip',
                SlackTeamId__c = 'board');

        TimeEntry__c skateboardYesterdayNineFifteen = new TimeEntry__c(
                Contact__c = skate.Id,
                StartTime__c = yesterdayNineFifteen,
                EndTime__c = yesterdayNineFifteen.addMinutes(30),
                SlackUserId__c = 'skate',
                SlackTeamId__c = 'board');

        TimeEntry__c skateboardYesterdayTenFifteen = new TimeEntry__c(
                Contact__c = skate.Id,
                StartTime__c = yesterdayTenFifteen,
                EndTime__c = yesterdayTenFifteen.addHours(7).addMinutes(30),
                SlackUserId__c = 'skate',
                SlackTeamId__c = 'board');

        insert new List<TimeEntry__c> {
            skateboardYesterdayNineFifteen,
            skateboardYesterdayTenFifteen,
            kickboard2DaysAgo,
            flipboard30mAgo
        };
    }
}