src/objects/ApexJobRequest__c.object
<CustomObject>
    <description>A request to execute a specific Apex job</description>
    <fields>
        <fullName>ApexClassName__c</fullName>
        <description>The name of the Apex class representing the job to execute</description>
        <inlineHelpText>The name of the Apex class representing the job to execute</inlineHelpText>
        <label>Apex Class Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Apex Job Request</label>
    <nameField>
        <displayFormat>AJR-{00000000}</displayFormat>
        <label>Apex Job Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <externalId>true</externalId>
        <label>Slack User ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/SlackTeamId__c.field-meta.xml
<CustomField>
    <fullName>SlackTeamId__c</fullName>
    <formula>Account.SlackTeamId__c</formula>
    <label>Slack Team ID</label>
    <type>Text</type>
</CustomField>

src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>EndTIme__c</fullName>
        <label>End TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/EndTimeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>EndTimeZoneSidKey__c</fullName>
    <description>The time zone in which the End Time was entered</description>
    <inlineHelpText>The time zone in which the End Time was entered</inlineHelpText>
    <label>End Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZoneSidKey</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/HasVerifiedEndTimeZone__c.field-meta.xml
<CustomField>
    <fullName>HasVerifiedEndTimeZone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the End Time Zone has been verified with the source of truth for the user&#39;s time zone</description>
    <inlineHelpText>Whether the End Time Zone has been verified with the source of truth for the user&#39;s time zone</inlineHelpText>
    <label>Verified End Time Zone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/TimeZoneSidKey.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Africa/Algiers</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Cairo</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Casablanca</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Johannesburg</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Nairobi</fullName>
    </customValue>
    <customValue>
        <fullName>America/Adak</fullName>
    </customValue>
    <customValue>
        <fullName>America/Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>America/Argentina/Buenos_Aires</fullName>
    </customValue>
    <customValue>
        <fullName>America/Bogota</fullName>
    </customValue>
    <customValue>
        <fullName>America/Caracas</fullName>
    </customValue>
    <customValue>
        <fullName>America/Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Denver</fullName>
    </customValue>
    <customValue>
        <fullName>America/El_Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>America/Halifax</fullName>
    </customValue>
    <customValue>
        <fullName>America/Indiana/Indianapolis</fullName>
    </customValue>
    <customValue>
        <fullName>America/Lima</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mazatlan</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mexico_City</fullName>
    </customValue>
    <customValue>
        <fullName>America/New_York</fullName>
    </customValue>
    <customValue>
        <fullName>America/Panama</fullName>
    </customValue>
    <customValue>
        <fullName>America/Phoenix</fullName>
    </customValue>
    <customValue>
        <fullName>America/Puerto_Rico</fullName>
    </customValue>
    <customValue>
        <fullName>America/Santiago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Sao_Paulo</fullName>
    </customValue>
    <customValue>
        <fullName>America/Scoresbysund</fullName>
    </customValue>
    <customValue>
        <fullName>America/St_Johns</fullName>
    </customValue>
    <customValue>
        <fullName>America/Tijuana</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baghdad</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baku</fullName>
    </customValue>
    <description>Time zone values matching what&#39;s stored by Salesforce on User records</description>
    <masterLabel>Time Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SlashclockOutCommandTest.cls
@isTest
private class SlashclockOutCommandTest {

    @isTest
    private static void clockOutFiveThirtyPm() {
        Test.setMock(HttpCalloutMock.class, new SlackApiServiceMockSuite());
        
        // Test setup
        DateTime setupTime = DateTime.now();
        TimeZone setupTimeZone = TimeZone.getTimeZone('America/New_York');

        RelativeTestService relativeTest =
                RelativeTestService.getInstance(
                        setupTime, setupTimeZone.getID());

        relativeTest.setup();

        // Given
        String slackUserId = 'kick';
        String slackTeamId = 'board';

        List<TimeEntry__c> openEntries = [
            SELECT
                EndTime__c,
                EndTimeZoneSidKey__c,
                StartTime__c,
                Id
            FROM TimeEntry__c
            WHERE
                EndTime__c = NULL AND
                Contact__r.SlackUserId__c = :slackUserId
        ];

        System.assertEquals(1, openEntries.size(), 'openEntries.size()');

        Datetime clockOutTime = DatetimeUtil.newDatetime(
                Date.today(),
                Time.newInstance(17, 30, 0, 0),
                'America/New_York');

        System.assert(openEntries[0].StartTime__c < clockOutTime,
                'clockOutTime must be later than open entry Start Time');

        System.assertEquals(
                null,
                openEntries[0].EndTime__c,
                Schema.SObjectType.TimeEntry__c.fields.EndTime__c.label);

        System.assertEquals(
                null,
                openEntries[0].EndTimeZoneSidKey__c,
                Schema.SObjectType.TimeEntry__c.fields.EndTimeZoneSidKey__c.label);

        SlashCommand__c slashCommand = new SlashCommand__c(
                SlackUserId__c = slackUserId,
                SlackTeamId__c = slackTeamId,
                Text__c = 'out 5:30pm');

        SlashclockOutCommand command = new SlashclockOutCommand();

        System.assert(command.matches(slashCommand),
                'must match slash command');

        // When
        Test.startTest();

        command.load(slashCommand);
        command.execute();

        // Then
        Test.stopTest();

        TimeEntry__c closedEntry = [
            SELECT
                EndTime__c,
                EndTimeZoneSidKey__c,
                HasVerifiedEndTimeZone__c,
                Id
            FROM TimeEntry__c
            WHERe Id = :openEntries[0].Id
        ];

        System.assertEquals(clockOutTime, closedEntry.EndTime__c,
                Schema.SObjectType.TimeEntry__c.fields.EndTime__c.label);

        System.assertEquals(
                'America/New_York',
                closedEntry.EndTimeZoneSidKey__c,
                Schema.SObjectType.TimeEntry__c.fields.EndTimeZoneSidKey__c.label);
    }

    /**
     * This test validates the verification of time zones, based on whether
     * an Apex Job Request record was created and also whether an
     * `ApexJobRequestProcessJob` batch is executed.
     */
    @isTest
    private static void clockOutFiveThirtyPmThenVerifyTimeZone() {
        Test.setMock(HttpCalloutMock.class, new SlackApiServiceMockSuite());
        
        // Test setup
        DateTime setupTime = DateTime.now();
        TimeZone setupTimeZone = TimeZone.getTimeZone('America/New_York');

        RelativeTestService relativeTest =
                RelativeTestService.getInstance(
                        setupTime, setupTimeZone.getID());

        relativeTest.setup();
        
        // Given
        String slackUserId = 'kick';
        String slackTeamId = 'board';

        // Find the contact for the Slack user
        SlackService slacker = SlackService.getInstance(slackTeamId);
        Contact userContact = slacker.findOrCreateContact(slackUserId);

        SlashclockService slashclock =
                SlashclockService.getInstance(userContact);

        Datetime clockOutTime = DatetimeUtil.newDatetime(
                Date.today(),
                Time.newInstance(17, 30, 0, 0),
                slashclock.getTimeZoneSidKey());

        SlashCommand__c slashCommand = new SlashCommand__c(
                SlackUserId__c = slackUserId,
                SlackTeamId__c = slackTeamId,
                Text__c = 'out 5:30pm');

        SlashclockOutCommand command = new SlashclockOutCommand();

        // Make sure no `ApexJobRequestProcessJob` batches are
        // already enqueued.
        System.assertEquals(0, [
            SELECT Id
            FROM AsyncApexJob
            WHERE
                ApexClassId IN (
                    SELECT Id
                    FROM ApexClass
                    WHERE Name = 'ApexJobRequestProcessJob'
                )
        ].size(), 'given count of ApexJobRequestProcessJob');

        // When
        Test.startTest();

        command.load(slashCommand);
        command.execute();

        // Then
        Test.stopTest();

        // Make sure one Apex Job Request record was created
        System.assertEquals(1, [
            SELECT Id
            FROM ApexJobRequest__c
            WHERE ApexClassName__c = :TimeEntryVerifyTimeZoneJob.class.getName()
        ].size(), 'then count of Apex Job Request');

        // Make sure one `ApexJobRequestProcessJob` batch is
        // executed and in the Apex job queue.
        System.assertEquals(1, [
            SELECT Id
            FROM AsyncApexJob
            WHERE
                ApexClassId IN (
                    SELECT Id
                    FROM ApexClass
                    WHERE Name = 'ApexJobRequestProcessJob'
                ) AND
                JobType = 'BatchApex'
        ].size(), 'then count of BatchApex jobs');

        // Make sure one `ApexJobRequestProcessJob` batch worker is
        // executed and in the Apex job queue.
        System.assertEquals(1, [
            SELECT Id
            FROM AsyncApexJob
            WHERE
                ApexClassId IN (
                    SELECT Id
                    FROM ApexClass
                    WHERE Name = 'ApexJobRequestProcessJob'
                ) AND
                JobType = 'BatchApexWorker'
        ].size(), 'then count of BatchApex jobs');
    }

    @isTest
    private static void clockOutYesterdayFiveThirtyPm() {
        Test.setMock(HttpCalloutMock.class, new SlackApiServiceMockSuite());
        
        // Test setup
        DateTime setupTime = DateTime.now();
        TimeZone setupTimeZone = TimeZone.getTimeZone('America/New_York');

        RelativeTestService relativeTest =
                RelativeTestService.getInstance(
                        setupTime, setupTimeZone.getID());

        relativeTest.setup();
        
        // Given
        String slackUserId = 'kick';
        String slackTeamId = 'board';

        // Find the contact for the Slack user
        SlackService slacker = SlackService.getInstance(slackTeamId);
        Contact userContact = slacker.findOrCreateContact(slackUserId);

        SlashclockService slashclock =
                SlashclockService.getInstance(userContact);

        List<TimeEntry__c> openEntries = slashclock.getOpenTimeEntries();

        System.assertEquals(1, openEntries.size(), 'openEntries.size()');

        Datetime clockOutTime = DatetimeUtil.newDatetime(
                Date.today().addDays(-1),
                Time.newInstance(17, 30, 0, 0),
                slashclock.getTimeZoneSidKey());

        System.assert(openEntries[0].StartTime__c < clockOutTime,
                'clockOutTime must be later than open entry Start Time');

        SlashCommand__c slashCommand = new SlashCommand__c(
                SlackUserId__c = slackUserId,
                SlackTeamId__c = slackTeamId,
                Text__c = 'out yesterday 5:30pm');

        SlashclockOutCommand command = new SlashclockOutCommand();

        System.assert(command.matches(slashCommand),
                'must match slash command');

        // When
        Test.startTest();

        command.load(slashCommand);
        command.execute();

        // Then
        Test.stopTest();

        TimeEntry__c closedEntry = [
            SELECT Id, EndTime__c
            FROM TimeEntry__c
            WHERe Id = :openEntries[0].Id
        ];

        System.assertEquals(clockOutTime, closedEntry.EndTime__c,
                Schema.SObjectType.TimeEntry__c.fields.EndTime__c.label);
    }
}