src/objects/ApexJobRequest__c.object
<CustomObject>
    <description>A request to execute a specific Apex job</description>
    <fields>
        <fullName>ApexClassName__c</fullName>
        <description>The name of the Apex class representing the job to execute</description>
        <inlineHelpText>The name of the Apex class representing the job to execute</inlineHelpText>
        <label>Apex Class Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <description>The JSON body of the request, which should be able to be deserialized into a new instance of the requested job</description>
        <inlineHelpText>The JSON body of the request, which should be able to be deserialized into a new instance of the requested job</inlineHelpText>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Exception.getMessage()</description>
        <inlineHelpText>Exception.getMessage()</inlineHelpText>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ErrorStackTrace__c</fullName>
        <description>Exception.getStackTraceString()</description>
        <inlineHelpText>Exception.getStackTraceString()</inlineHelpText>
        <label>Error Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Submitted&apos;</defaultValue>
        <description>The current status of the request. A request starts in &quot;Submitted&quot;, after the request is processed the status will change to either &quot;Success&quot; or &quot;Error&quot;.</description>
        <inlineHelpText>The current status of the request</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Apex Job Request</label>
    <nameField>
        <displayFormat>AJR-{00000000}</displayFormat>
        <label>Apex Job Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexJobServiceTest.cls
@isTest
private class ApexJobServiceTest {

    @isTest
    private static void submitTimeEntryVerifyTimeZoneJob() {

        // Given
        TimeEntryVerifyTimeZoneJob job =
                new TimeEntryVerifyTimeZoneJob(new List<Id>());

        // When
        Test.startTest();

        Id requestId = ApexJobService.getInstance(
                TimeEntryVerifyTimeZoneJob.class).submit(job);

        // Then
        Test.stopTest();

        ApexJobRequest__c thenRequest = getApexJobRequest(requestId);

        System.assertEquals(
                TimeEntryVerifyTimeZoneJob.class.getName(),
                thenRequest.ApexClassName__c,
                Schema.SObjectType.ApexJobRequest__c.fields.ApexClassName__c.label);

        System.assertEquals(
                '{"contactIds":[]}',
                thenRequest.Body__c,
                Schema.SObjectType.ApexJobRequest__c.fields.Body__c.label);
    }

    private static ApexJobRequest__c getApexJobRequest(Id recordId) {
        return [
            SELECT
                ApexClassName__c,
                Body__c,
                ErrorMessage__c,
                ErrorStackTrace__c,
                Status__c,
                Id
            FROM ApexJobRequest__c
            WHERE Id = :recordId
        ];
    }
}