src/objects/ApexJobRequest__c.object
<CustomObject>
    <description>A request to execute a specific Apex job</description>
    <fields>
        <fullName>ApexClassName__c</fullName>
        <description>The name of the Apex class representing the job to execute</description>
        <inlineHelpText>The name of the Apex class representing the job to execute</inlineHelpText>
        <label>Apex Class Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <description>The JSON body of the request, which should be able to be deserialized into a new instance of the requested job</description>
        <inlineHelpText>The JSON body of the request, which should be able to be deserialized into a new instance of the requested job</inlineHelpText>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Exception.getMessage()</description>
        <inlineHelpText>Exception.getMessage()</inlineHelpText>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Submitted&apos;</defaultValue>
        <description>The current status of the request. A request starts in &quot;Submitted&quot;, after the request is processed the status will change to either &quot;Success&quot; or &quot;Error&quot;.</description>
        <inlineHelpText>The current status of the request</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Apex Job Request</label>
    <nameField>
        <displayFormat>AJR-{00000000}</displayFormat>
        <label>Apex Job Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexJobRequestProcessJobTest.cls
@isTest
private class ApexJobRequestProcessJobTest {

    @isTest
    private static void processEmptyVerifyTimeZoneJob() {

        // Given
        TestService thisTest = TestService.getInstance();

        ApexJobRequest__c givenRequest = new ApexJobRequest__c(
                ApexClassName__c = TimeEntryVerifyTimeZoneJob.class.getName(),
                Body__c = JSON.serialize(
                        new TimeEntryVerifyTimeZoneJob(new List<Id>())));

        insert givenRequest;

        System.assertEquals(
                'Submitted',
                thisTest.getApexJobRequest(givenRequest).Status__c,
                Schema.SObjectType.ApexJobRequest__c.fields.Status__c.label);

        // When
        Test.startTest();

        Database.executeBatch(new ApexJobRequestProcessJob());

        // Then
        Test.stopTest();

        System.assertEquals(
                'Success',
                thisTest.getApexJobRequest(givenRequest).Status__c,
                Schema.SObjectType.ApexJobRequest__c.fields.Status__c.label);
    }

    @isTest
    private static void processInvalidJob() {

        // Given
        TestService thisTest = TestService.getInstance();
        
        ApexJobRequest__c givenRequest = new ApexJobRequest__c(
                ApexClassName__c = 'DoesNotExistJob',
                Body__c = 'foobar');

        insert givenRequest;

        System.assertEquals(
                'Submitted',
                thisTest.getApexJobRequest(givenRequest).Status__c,
                Schema.SObjectType.ApexJobRequest__c.fields.Status__c.label);

        // When
        Test.startTest();

        Database.executeBatch(new ApexJobRequestProcessJob());

        // Then
        Test.stopTest();

        System.assertEquals(
                'Error',
                thisTest.getApexJobRequest(givenRequest).Status__c,
                Schema.SObjectType.ApexJobRequest__c.fields.Status__c.label);

        System.assertEquals(
                'Attempt to de-reference a null object',
                thisTest.getApexJobRequest(givenRequest).ErrorMessage__c,
                Schema.SObjectType.ApexJobRequest__c.fields.ErrorMessage__c.label);
    }
}