src/objects/ApexJobRequest__c.object
<CustomObject>
    <description>A request to execute a specific Apex job</description>
    <fields>
        <fullName>ApexClassName__c</fullName>
        <description>The name of the Apex class representing the job to execute</description>
        <inlineHelpText>The name of the Apex class representing the job to execute</inlineHelpText>
        <label>Apex Class Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <description>The JSON body of the request, which should be able to be deserialized into a new instance of the requested job</description>
        <inlineHelpText>The JSON body of the request, which should be able to be deserialized into a new instance of the requested job</inlineHelpText>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <description>Exception.getMessage()</description>
        <inlineHelpText>Exception.getMessage()</inlineHelpText>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ErrorStackTrace__c</fullName>
        <description>Exception.getStackTraceString()</description>
        <inlineHelpText>Exception.getStackTraceString()</inlineHelpText>
        <label>Error Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&apos;Submitted&apos;</defaultValue>
        <description>The current status of the request. A request starts in &quot;Submitted&quot;, after the request is processed the status will change to either &quot;Success&quot; or &quot;Error&quot;.</description>
        <inlineHelpText>The current status of the request</inlineHelpText>
        <label>Status</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Apex Job Request</label>
    <nameField>
        <displayFormat>AJR-{00000000}</displayFormat>
        <label>Apex Job Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Job Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexJobRequestProcessJob.cls
global class ApexJobRequestProcessJob
        implements Database.Batchable<SObject> {

    global void execute(Database.BatchableContext context, List<SObject> records) {
        for (ApexJobRequest__c eachRequest : (List<ApexJobRequest__c>)records) {
            try {
                Requestable job =
                        (Requestable)JSON.deserialize(
                                eachRequest.Body__c,
                                Type.forName(eachRequest.ApexClassName__c));

                job.execute(context);
                eachRequest.Status__c = 'Success';
            }
            catch (System.Exception caught) {
                eachRequest.Status__c = 'Error';
                eachRequest.ErrorMessage__c = caught.getMessage();
                eachRequest.ErrorStackTrace__c = caught.getStackTraceString();
            }
        }

        update records;
    }

    global void finish(Database.BatchableContext context) {
        /* do nothing */
    }

    global Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
            SELECT
                ApexClassName__c,
                Body__c,
                Status__c,
                Id
            FROM ApexJobRequest__c
            WHERE Status__c = 'Submitted'
        ]);
    }
}