src/objects/Connection__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Connection settings for invoking external APIs</description>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>Client ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Connection</label>
</CustomObject>

src/classes/SlackApiServiceTest.cls
@isTest
private class SlackApiServiceTest {

    @isTest
    private static void oauthAccess() {

        // Given
        Connection__c connection = new Connection__c(
                ClientId__c = 'test-id',
                ClientSecret__c = 'test-secret');

        String code = 'test-code';

        // When
        Test.setMock(HttpCalloutMock.class, new OauthAccessMock());
        Test.startTest();

        SlackApi.OauthAccessResponse oauthAccess =
                new SlackApiService().oauthAccess(connection, code);

        // Then
        Test.stopTest();

        System.assertEquals(
                'xoxp-23984754863-2348975623103',
                oauthAccess.access_token,
                'OauthAccessResponse.access_token');

        System.assertEquals(
                'read',
                oauthAccess.scope,
                'OauthAccessResponse.scope');
    }

    private class OauthAccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {

            // Construct the response
            HttpResponse res = new HttpResponse();

            res.setBody([
                SELECT Body
                FROM StaticResource
                WHERE Name = 'SlackApiOauthAccessMock'
            ].Body.toString());

            // Return the response
            return res;
        }
    }
}