src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <externalId>true</externalId>
        <label>Slack User ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/SlackTeamId__c.field-meta.xml
<CustomField>
    <fullName>SlackTeamId__c</fullName>
    <formula>Account.SlackTeamId__c</formula>
    <label>Slack Team ID</label>
    <type>Text</type>
</CustomField>

src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClockResource.cls
@RestResource(urlMapping='/clock')
global class ClockResource {

    @HttpPost
    global static Slack.SlashCommandResponse post() {

        // Process the request
        SlashCommand__c slash = SlashCommandUtil.parse(RestContext.request);

        // Find the contact for the Slack user
        SlackService slacker = SlackService.getInstance(slash.SlackTeamId__c);
        Contact userContact = slacker.findOrCreateContact(slash.SlackUserId__c);

        SlashclockService slashclock = SlashclockService.getInstance(userContact);
        Slashclock.CommandResult result = slashclock.execute(slash);

        // Return the response
        RestContext.response.addHeader('Content-Type', 'application/json');
        return new Slack.SlashCommandResponse(result.getMessage());
    }
}