src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <externalId>true</externalId>
        <label>Slack User ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/SlackTeamId__c.field-meta.xml
<CustomField>
    <fullName>SlackTeamId__c</fullName>
    <formula>Account.SlackTeamId__c</formula>
    <label>Slack Team ID</label>
    <type>Text</type>
</CustomField>

src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SlashclockReportCommand.cls
public with sharing class SlashclockReportCommand implements Slashclock.Command {

    private DateTime endTime;
    private Boolean forLastWeek;
    private Contact userContact;

    public SlashclockReportCommand() {
        this.endTime = DateTime.now();
        this.forLastWeek = false;
        this.userContact = null;
    }

    public Slashclock.CommandResult execute() {

        // Initialize the result
        Slashclock.CommandResult result = new Slashclock.CommandResult();

        // Get the service
        SlashclockService slashclock =
                SlashclockService.getInstance(this.userContact);

        // Adjust for last week if needed
        if (this.forLastWeek) {
            this.endTime = slashclock.getStartOfWeek(
                    this.endTime).addSeconds(-1);
        }
        else {

            // TODO: Make the scale configurable per user
            this.endTime = DatetimeUtil.setScale(this.endTime, 6);
        }

        // Generate the report
        SlashclockReport report = slashclock.report(this.endTime);
        result.setMessage(SlackUtil.format(report));
        result.setSuccess(true);

        // Return the result
        return result;
    }

    public Slashclock.Command load(SlashCommand__c command) {
        
        // Find the contact for the Slack user
        SlackService slacker = SlackService.getInstance(command.SlackTeamId__c);
        this.userContact = slacker.findOrCreateContact(command.SlackUserId__c);

        // Set the end time to the start of this week, so that the report
        // will contain all entries from the previous week.
        if (command.Text__c.endsWith('last week')) {
            this.forLastWeek = true;
        }

        return this;
    }

    public Boolean matches(SlashCommand__c command) {
        return command.Text__c.startsWith('report');
    }
}