src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlashclockHelpCommandTest.cls
@isTest
private class SlashclockHelpCommandTest {

    /**
     * /clock help
     */
    @isTest
    private static void clockHelp() {
        
        // Given
        String slackUserId = 'em';
        String slackTeamId = 'cee';

        SlashclockService slashclock =
                SlashclockService.getInstance(slackUserId, slackTeamId);

        SlashCommand__c slashCommand = new SlashCommand__c(
                SlackUserId__c = slackUserId,
                SlackTeamId__c = slackTeamId,
                Text__c = 'help');

        SlashclockHelpCommand command = new SlashclockHelpCommand();

        System.assert(command.matches(slashCommand),
                'must match slash command');

        // When
        Test.startTest();

        command.load(slashCommand);
        Slashclock.CommandResult result = command.execute();

        // Then
        Test.stopTest();

        System.assertEquals(true, result.isSuccess(), 'result.isSuccess()');

        System.assertEquals(
                'Content for */clock help*',
                result.getMessage(),
                'result.getMessage()');
    }

    /**
     * /clock help in
     */
    @isTest
    private static void clockHelpIn() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help out
     */
    @isTest
    private static void clockHelpOut() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help report
     */
    @isTest
    private static void clockHelpReport() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help slice
     */
    @isTest
    private static void clockHelpSlice() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help entries
     */
    @isTest
    private static void clockHelpEntries() {
        System.assert(false, 'TODO');
    }

    /**
     * /clock help strike
     */
    @isTest
    private static void clockHelpStrike() {
        System.assert(false, 'TODO');
    }

    @testSetup
    private static void setup() {
        TestService.getInstance().setup();
    }
}