src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlashclockHelpCommand.cls
public with sharing class SlashclockHelpCommand implements Slashclock.Command {

    /**
     * The subcommand that comes after `/clock help` as issued by the user
     */
    private String subcommandText;

    public SlashclockHelpCommand() {
        this.subcommandText = null;
    }

    public Slashclock.CommandResult execute() {

        // Get the content type and appropriate content based on the subcommand
        SlashclockContentName contentName =
                SlashclockContentUtil.getHelpContentName(this.subcommandText);

        SlashclockContentService slashclockContent =
                SlashclockContentService.getInstance();

        // Construct a success result
        Slashclock.CommandResult result = new Slashclock.CommandResult();

        result.setSuccess(true);
        result.setMessage(slashclockContent.getContent(contentName));

        // Return the result
        return result;
    }

    public Slashclock.Command load(SlashCommand__c command) {
        return this;
    }

    public Boolean matches(SlashCommand__c command) {
        return command.Text__c.startsWith('help');
    }
}