src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlashclockUnknownCommandTest.cls
@isTest
private class SlashclockUnknownCommandTest {

    /**
     * What happens when you /clock foo?
     */
    @isTest
    private static void clockFoo() {
        
        // Given
        String slackUserId = 'em';
        String slackTeamId = 'cee';

        SlashclockService slashclock =
                SlashclockService.getInstance(slackUserId, slackTeamId);

        SlashCommand__c slashCommand = new SlashCommand__c(
                SlackUserId__c = slackUserId,
                SlackTeamId__c = slackTeamId,
                Command__c = '/clock',
                Text__c = 'foo');

        Slashclock.Command command = new SlashclockUnknownCommand();

        System.assert(command.matches(slashCommand),
                'must match slash command');

        // When
        Test.startTest();

        command.load(slashCommand);
        Slashclock.CommandResult result = command.execute();

        // Then
        Test.stopTest();

        System.assertEquals(false, result.isSuccess(), 'result.isSuccess()');

        System.assertEquals(
                'Unknown command, /clock foo!',
                result.getMessage(),
                'result.getMessage()');
    }

    @testSetup
    private static void setup() {
        TestService.getInstance().setup();
    }
}