src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlashclockUnknownCommand.cls
public class SlashclockUnknownCommand implements Slashclock.Command {

    public Slashclock.CommandResult execute() {

        // Initialize the result
        Slashclock.CommandResult result = new Slashclock.CommandResult();

        result.setSuccess(false);  // If we got here, things are not okay

        // Set the error message
        SlashclockContentService slashclockContent =
                SlashclockContentService.getInstance();

        result.setMessage(
                slashclockContent.getContent(
                        SlashclockContentName.UNKNOWN_COMMAND));

        // Return the result
        return result;
    }

    public Slashclock.Command load(SlashCommand__c command) {
        return this;
    }

    public Boolean matches(SlashCommand__c command) {
        return command.Command__c == '/clock';
    }
}