src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>EndTIme__c</fullName>
        <label>End TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlice__c/TimeSlice__c.object-meta.xml
<CustomObject>
    <label>Time Slice</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Time Slice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlice__c/fields/TimeEntry__c.field-meta.xml
<CustomField>
    <fullName>TimeEntry__c</fullName>
    <label>Time Entry</label>
    <referenceTo>TimeEntry__c</referenceTo>
    <relationshipLabel>Time Slices</relationshipLabel>
    <relationshipName>TimeSlices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/SlashclockUtil.cls
public with sharing class SlashclockUtil {
    public static List<Slashclock.Command> getKnownCommands() {
        return new List<Slashclock.Command> {
            new SlashclockInCommand(),
            new SlashclockOutCommand(),
            new SlashclockReportCommand()
        };
    }

    public static Slashclock.Command newCommand(SlashCommand__c command) {

        // Placeholder for the command to return
        Slashclock.Command matchedCommand = null;

        // Go through all known commands to look for a match
        List<Slashclock.Command> knownCommands = getKnownCommands();

        while (matchedCommand == null && knownCommands.size() > 0) {
            Slashclock.Command knownCommand = knownCommands.remove(0);
            if (knownCommand.matches(command)) {
                matchedCommand = knownCommand.load(command);
            }
        }

        // Return the matched command
        return matchedCommand;
    }

    /**
     * @param startTime the start of the first day
     * @param endTime the reference time to use in case an open time entry
     *                needs to be closed out
     * @param timeZoneSidKey
     * @param entries the list of time entries to convert into report items.
     *                the entries in this list are all assumed to fall within
     *                the `startTime`-`endTime` range, and the entries are
     *                also expected to include related slices.
     * @param numberOfDays
     *            The number of days to include in the list
     *
     * @return the list of report items representing the 
     */
    public static List<SlashclockReportItem> newDailyReportItems(
            DateTime startTime, DateTime endTime, String timeZoneSidKey,
            List<TimeEntry__c> entries, Integer numberOfDays) {

        // Initialize the list
        List<SlashclockReportItem> items = new List<SlashclockReportItem>();

        // Figure out the start times for every day in the report range
        List<DateTime> dailyStartTimes = new List<DateTime> { startTime };

        while (dailyStartTimes.size() < numberOfDays) {
            dailyStartTimes.add(
                    dailyStartTimes.get(
                            dailyStartTimes.size() - 1).addDays(1));
        }

        // Go through all of the days we're tracking and figure out
        // which time entries to incorporate into the day's hours
        for (DateTime eachStartTime : dailyStartTimes) {

            // Initialize a report item for the start time
            SlashclockReportItem item = SlashclockReportItem.newInstance(
                    eachStartTime, timeZoneSidKey, Time2.newInstance());

            // Incorporate every qualifying time entry into the report item
            for (TimeEntry__c eachEntry
                    : qualify(entries, startTime, startTime.addDays(1))) {

                // Add the time entry's duration
                DateTime effectiveEndTime = eachEntry.EndTime__c == null
                        ? endTime : eachEntry.EndTime__c;

                item.addDuration(
                        effectiveEndTime.getTime()
                                - eachEntry.StartTime__c.getTime());

                // Add all of the time entry's slices
                for (TimeSlice__c eachSlice : eachEntry.TimeSlices__r) {
                    item.addSlice(SlashclockReportSlice.newInstance(eachSlice));
                }
            }

            // Add the report item
            items.add(item);
        }

        // Return the final list
        return items;
    }

    public static SlashclockService.Key newServiceKey(SlashCommand__c command) {
        return new SlashclockService.Key(command.SlackUserId__c, command.SlackTeamId__c);
    }

    public static List<TimeEntry__c> qualify(
            List<TimeEntry__c> entries, DateTime startTime, DateTime endTime) {

        // Initialize the list of qualified time entries
        List<TimeEntry__c> qualified = new List<TimeEntry__c>();

        // Check the given entries
        for (TimeEntry__c eachEntry : entries) {
            if (eachEntry.StartTime__c >= startTime
                    && eachEntry.StartTime__c < endTime) {
                qualified.add(eachEntry);
            }
        }

        // Return the list of qualified time entries
        return qualified;
    }
}