src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SlashclockFeedbackCommandTest.cls
@isTest
private class SlashclockFeedbackCommandTest {

    @isTest
    private static void matchesFeedback() {

        // Given
        Map<String, Boolean> expectedMap = new Map<String, Boolean> {
            'feedback' => true,
            'feed' => false,
            'feedback ' => true,
            'feedback test' => true
        };

        // When
        Test.startTest();

        Map<String, Boolean> actualMap = new Map<String, Boolean>();

        for (String eachKey : expectedMap.keySet()) {

            // Construct the slash command
            SlashCommand__c slash = new SlashCommand__c(
                    Command__c = '/clock',
                    Text__c = eachKey);

            // Check the match
            actualMap.put(
                    eachKey,
                    new SlashclockFeedbackCommand().matches(slash));
        }

        // Then
        Test.stopTest();

        for (String eachKey : expectedMap.keySet()) {
            Boolean expected = expectedMap.get(eachKey);
            Boolean actual = actualMap.get(eachKey);

            System.assertEquals(expected, actual, eachKey);
        }
    }

    @isTest
    private static void throwNoMessageException() {

        // Given
        SlashCommand__c slash = new SlashCommand__c(
                Command__c = '/clock',
                SlackTeamId__c = 'ateam',
                SlackUserId__c = 'auser',
                Text__c = 'feedback');

        // When
        Test.startTest();

        SlashclockException caught = null;

        try {
            new SlashclockFeedbackCommand().load(slash);
        }
        catch (SlashclockException thrown) {
            caught = thrown;
        }

        // Then
        Test.stopTest();

        System.assertEquals(
                Label.SlashclockFeedbackNoMessage,
                caught.getMessage(),
                SlashclockException.class.getName());
    }

    @isTest
    private static void execute() {

        // Given
        SlashCommand__c slash = new SlashCommand__c(
                Command__c = '/clock',
                SlackTeamId__c = 'ateam',
                SlackUserId__c = 'auser',
                Text__c = 'feedback :thumbsup:');

        // When
        Test.startTest();

        Slashclock.CommandResult result =
                new SlashclockFeedbackCommand().load(slash).execute();

        // Then
        Test.stopTest();

        System.assertEquals(
                Label.SlashclockFeedbackSuccess,
                result.getMessage(),
                'result message');

        System.assertEquals(
                true,
                result.isSuccess(),
                'result success');
    }
}