src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/DurationMinutes__c.field-meta.xml
<CustomField>
    <fullName>DurationMinutes__c</fullName>
    <formula>DurationHours__c * 60</formula>
    <label>Duration (Min)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/NumberOfSlicedMinutes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfSlicedMinutes__c</fullName>
    <label>Total Sliced Minutes</label>
    <summarizedField>TimeSlice__c.NumberOfMinutes__c</summarizedField>
    <summaryForeignKey>TimeSlice__c.TimeEntry__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TimeSlice__c/TimeSlice__c.object-meta.xml
<CustomObject>
    <label>Time Slice</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Time Slice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlice__c/fields/NumberOfMinutes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfMinutes__c</fullName>
    <label>Num Minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeSlice__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSlice__c/fields/TimeEntry__c.field-meta.xml
<CustomField>
    <fullName>TimeEntry__c</fullName>
    <label>Time Entry</label>
    <referenceTo>TimeEntry__c</referenceTo>
    <relationshipLabel>Time Slices</relationshipLabel>
    <relationshipName>TimeSlices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SlashclockSliceCommandTest.cls
@isTest
private class SlashclockSliceCommandTest {

    /**
     * Given two time entries, with the last one being open with no slices;
     * When a new "slice" command is executed for 30 minutes tagged "test";
     * Then a new time slice should be created under the open time entry
     * showing 30 minutes tagged "test"
     *
     * @see https://api.slack.com/slash-commands
     */
    @isTest
    private static void sliceOpenEntry30Minutes() {

        // Test setup
        TestService.getInstance().setupSlashclockSliceCommandTest();
        
        // Given
        TimeEntry__c givenEntry = [
            SELECT Id,
                (
                    SELECT Id, NumberOfMinutes__c, Tag__c
                    FROM TimeSlices__r
                )
            FROM TimeEntry__c
            WHERE SlackUserId__c = 'bugs'
            AND SlackTeamId__c = 'acme'
            ORDER BY StartTime__c DESC
            LIMIT 1
        ];

        System.assertEquals(0, givenEntry.TimeSlices__r.size(),
                'given entry should have no slices');

        // When
        Test.startTest();

        SlashCommand__c inboundCommand = new SlashCommand__c(
                Command__c = '/clock',
                Text__c = 'slice 30 minutes test',
                SlackTeamId__c = 'acme',
                SlackUserId__c = 'bugs');

        SlashclockUtil.newCommand(inboundCommand).execute();

        // Then
        Test.stopTest();

        TimeEntry__c thenEntry = [
            SELECT Id,
                (
                    SELECT Id, NumberOfMinutes__c, Tag__c
                    FROM TimeSlices__r
                )
            FROM TimeEntry__c
            WHERE Id = :givenEntry.Id
        ];

        System.assertEquals(1 ,thenEntry.TimeSlices__r.size(),
                'then entry should have one slice');

        System.assertEquals(30, thenEntry.TimeSlices__r[0].NumberOfMinutes__c,
                Schema.SObjectType.TimeSlice__c.fields.NumberOfMinutes__c.label);

        System.assertEquals('test', thenEntry.TimeSlices__r[0].Tag__c,
                Schema.SObjectType.TimeSlice__c.fields.Tag__c.label);
    }

    /**
     * Given one closed time entry for 1 hour having a 30-minute slice;
     * When a new "slice" command is executed for 30 minutes tagged "test";
     * Then a new time slice should be created under the open time entry
     * showing 30 minutes tagged "test"
     */
    @isTest
    private static void sliceClosedEntry30MinutesSuccess() {

        // Test setup
        TestService.getInstance().setupSlashclockSliceCommandTest();
        
        // Given
        TimeEntry__c givenEntry = [
            SELECT Id, DurationMinutes__c, NumberOfSlicedMinutes__c,
                (
                    SELECT Id, NumberOfMinutes__c, Tag__c
                    FROM TimeSlices__r
                    ORDER BY CreatedDate ASC
                )
            FROM TimeEntry__c
            WHERE SlackTeamId__c = 'acme'
            AND SlackUserId__c = 'daffy'
            ORDER BY StartTime__c DESC
            LIMIT 1
        ];

        System.assertEquals(60, givenEntry.DurationMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.DurationMinutes__c.label);

        System.assertEquals(30, givenEntry.NumberOfSlicedMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.NumberOfSlicedMinutes__c.label);

        System.assertEquals(1, givenEntry.TimeSlices__r.size(),
                'given entry should have one slice');

        System.assertEquals(30, givenEntry.TimeSlices__r[0].NumberOfMinutes__c,
                Schema.SObjectType.TimeSlice__c.fields.NumberOfMinutes__c.label);

        System.assertEquals('alpha', givenEntry.TimeSlices__r[0].Tag__c,
                Schema.SObjectType.TimeSlice__c.fields.Tag__c.label);

        // When
        Test.startTest();

        SlashCommand__c inboundCommand = new SlashCommand__c(
                Command__c = '/clock',
                Text__c = 'slice 30 minutes test',
                SlackTeamId__c = 'acme',
                SlackUserId__c = 'daffy');

        SlashclockUtil.newCommand(inboundCommand).execute();

        // Then
        Test.stopTest();

        TimeEntry__c thenEntry = [
            SELECT Id, DurationMinutes__c, NumberOfSlicedMinutes__c,
                (
                    SELECT Id, NumberOfMinutes__c, Tag__c
                    FROM TimeSlices__r
                )
            FROM TimeEntry__c
            WHERE Id = :givenEntry.Id
        ];

        System.assertEquals(60, thenEntry.DurationMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.DurationMinutes__c.label);

        System.assertEquals(60, thenEntry.NumberOfSlicedMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.NumberOfSlicedMinutes__c.label);

        System.assertEquals(2 ,thenEntry.TimeSlices__r.size(),
                'then entry should have two slices');

        Boolean has30MinutesTestSlice = false;

        for (TimeSlice__c eachSlice : thenEntry.TimeSlices__r) {
            if (eachSlice.NumberOfMinutes__c == 30 && eachSlice.Tag__c == 'test') {
                has30MinutesTestSlice = true;
            }
        }

        System.assert(has30MinutesTestSlice, 'then entry should have 30-minute test slice');
    }

    /**
     * Given one closed time entry for 1 hour having a 30-minute slice;
     * When a new "slice" command is executed for 31 minutes tagged "test";
     * Then an error should be raised indicating the total sliced duration
     * cannot be longer than the time entry itself
     */
    @isTest
    private static void sliceClosedEntry31MinutesError() {

        // Test setup
        TestService.getInstance().setupSlashclockSliceCommandTest();
        
        // Given
        TimeEntry__c givenEntry = [
            SELECT Id, DurationMinutes__c, NumberOfSlicedMinutes__c,
                (
                    SELECT Id, NumberOfMinutes__c, Tag__c
                    FROM TimeSlices__r
                    ORDER BY CreatedDate ASC
                )
            FROM TimeEntry__c
            WHERE SlackTeamId__c = 'acme'
            AND SlackUserId__c = 'daffy'
            ORDER BY StartTime__c DESC
            LIMIT 1
        ];

        System.assertEquals(60, givenEntry.DurationMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.DurationMinutes__c.label);

        System.assertEquals(30, givenEntry.NumberOfSlicedMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.NumberOfSlicedMinutes__c.label);

        System.assertEquals(1, givenEntry.TimeSlices__r.size(),
                'given entry should have one slice');

        System.assertEquals(30, givenEntry.TimeSlices__r[0].NumberOfMinutes__c,
                Schema.SObjectType.TimeSlice__c.fields.NumberOfMinutes__c.label);

        System.assertEquals('alpha', givenEntry.TimeSlices__r[0].Tag__c,
                Schema.SObjectType.TimeSlice__c.fields.Tag__c.label);

        // When
        Test.startTest();

        SlashCommand__c inboundCommand = new SlashCommand__c(
                Command__c = '/clock',
                Text__c = 'slice 31 minutes test',
                SlackTeamId__c = 'acme',
                SlackUserId__c = 'daffy');

        Slashclock.CommandResult result =
                SlashclockUtil.newCommand(inboundCommand).execute();

        // Then
        Test.stopTest();

        TimeEntry__c thenEntry = [
            SELECT Id, DurationMinutes__c, NumberOfSlicedMinutes__c,
                (
                    SELECT Id, NumberOfMinutes__c, Tag__c
                    FROM TimeSlices__r
                )
            FROM TimeEntry__c
            WHERE Id = :givenEntry.Id
        ];

        System.assertEquals(60, thenEntry.DurationMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.DurationMinutes__c.label);

        System.assertEquals(30, thenEntry.NumberOfSlicedMinutes__c,
                Schema.SObjectType.TimeEntry__c.fields.NumberOfSlicedMinutes__c.label);

        System.assertEquals(1 ,thenEntry.TimeSlices__r.size(),
                'then entry should still only have one slice');

        System.assertEquals(givenEntry.TimeSlices__r[0].Id, thenEntry.TimeSlices__r[0].Id,
                'then entry slice should be same as given entry slice');

        System.assertEquals(false, result.isSuccess(),
                'result should indicate NOT success');
    }
}