src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>EndTIme__c</fullName>
        <label>End TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlashclockStrikeCommandTest.cls
@isTest
private class SlashclockStrikeCommandTest {

    @testSetup
    private static void setup() {
        TestService.getInstance().setup();
    }

    /**
     * Delete the most recent time entry
     */
    @isTest
    private static void strikeFirstEntry() {

        // Given
        SlashCommand__c command = new SlashCommand__c(
                SlackUserId__c = 'flip',
                SlackTeamId__c = 'board',
                Command__c = '/clock',
                Text__c = 'strike 1');

        List<TimeEntry__c> givenEntries = [
            SELECT Id, StartTime__c, EndTime__c
            FROM TimeEntry__c
            WHERE SlackUserId__c = :command.SlackUserId__c
                AND SlackTeamId__c = :command.SlackTeamId__c
                AND StartTime__c >= :DateTime.now().addDays(-7)
        ];

        System.assertEquals(1, givenEntries.size());

        // When
        Test.startTest();

        Slashclock.CommandResult result =
                new SlashclockStrikeCommand().load(command).execute();

        // Then
        Test.stopTest();

        List<TimeEntry__c> thenEntries = [
            SELECT Id, StartTime__c, EndTime__c
            FROM TimeEntry__c
            WHERE SlackUserId__c = :command.SlackUserId__c
                AND SlackTeamId__c = :command.SlackTeamId__c
                AND StartTime__c >= :DateTime.now().addDays(-7)
        ];

        System.assertEquals(0, thenEntries.size());

        System.assert(result.getMessage().startsWith('Entry deleted.\n1.'),
                'message does not start as expected: ' + result.getMessage());
    }
}