src/objects/SlashCommand__c.object
<CustomObject>
    <description>Slack commands sent to the API</description>
    <fields>
        <fullName>Command__c</fullName>
        <description>Exact slash command, issued by the user</description>
        <label>Command</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <description>Serialized request as received by Salesforce</description>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>Text following the command, if given by the user</description>
        <label>Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Slack Command</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Slack Command Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slack Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SlashCommandUtil.cls
public with sharing class SlashCommandUtil {
    public static final String COMMAND_PARAM = 'command';
    public static final String TEAM_ID_PARAM = 'team_id';
    public static final String TEXT_PARAM = 'text';
    public static final String USER_ID_PARAM = 'user_id';
    
    public static SlashCommand__c parse(RestRequest req) {
        SlashCommand__c command = new SlashCommand__c();
        command.Request__c = JSON.serialize(req);
        command.Command__c = req.params.get(COMMAND_PARAM);
        command.Text__c = req.params.get(TEXT_PARAM);
        command.SlackUserId__c = req.params.get(USER_ID_PARAM);
        command.SlackTeamId__c = req.params.get(TEAM_ID_PARAM);
        return command;
    }
}