src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>EndTIme__c</fullName>
        <label>End TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/EndTimeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>EndTimeZoneSidKey__c</fullName>
    <description>The time zone in which the End Time was entered</description>
    <inlineHelpText>The time zone in which the End Time was entered</inlineHelpText>
    <label>End Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZoneSidKey</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/HasVerifiedEndTimeZone__c.field-meta.xml
<CustomField>
    <fullName>HasVerifiedEndTimeZone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the End Time Zone has been verified with the source of truth for the user&#39;s time zone</description>
    <inlineHelpText>Whether the End Time Zone has been verified with the source of truth for the user&#39;s time zone</inlineHelpText>
    <label>Verified End Time Zone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/HasVerifiedStartTimeZone__c.field-meta.xml
<CustomField>
    <fullName>HasVerifiedStartTimeZone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Start Time Zone has been verified with the source of truth for the user&#39;s time zone</description>
    <inlineHelpText>Whether the Start Time Zone has been verified with the source of truth for the user&#39;s time zone</inlineHelpText>
    <label>Verified Start Time Zone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTimeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>StartTimeZoneSidKey__c</fullName>
    <description>The time zone in which the Start Time was entered</description>
    <inlineHelpText>The time zone in which the Start Time was entered</inlineHelpText>
    <label>Start Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZoneSidKey</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TimeZoneSidKey.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Africa/Algiers</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Cairo</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Casablanca</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Johannesburg</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Nairobi</fullName>
    </customValue>
    <customValue>
        <fullName>America/Adak</fullName>
    </customValue>
    <customValue>
        <fullName>America/Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>America/Argentina/Buenos_Aires</fullName>
    </customValue>
    <customValue>
        <fullName>America/Bogota</fullName>
    </customValue>
    <customValue>
        <fullName>America/Caracas</fullName>
    </customValue>
    <customValue>
        <fullName>America/Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Denver</fullName>
    </customValue>
    <customValue>
        <fullName>America/El_Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>America/Halifax</fullName>
    </customValue>
    <customValue>
        <fullName>America/Indiana/Indianapolis</fullName>
    </customValue>
    <customValue>
        <fullName>America/Lima</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mazatlan</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mexico_City</fullName>
    </customValue>
    <customValue>
        <fullName>America/New_York</fullName>
    </customValue>
    <customValue>
        <fullName>America/Panama</fullName>
    </customValue>
    <customValue>
        <fullName>America/Phoenix</fullName>
    </customValue>
    <customValue>
        <fullName>America/Puerto_Rico</fullName>
    </customValue>
    <customValue>
        <fullName>America/Santiago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Sao_Paulo</fullName>
    </customValue>
    <customValue>
        <fullName>America/Scoresbysund</fullName>
    </customValue>
    <customValue>
        <fullName>America/St_Johns</fullName>
    </customValue>
    <customValue>
        <fullName>America/Tijuana</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baghdad</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baku</fullName>
    </customValue>
    <description>Time zone values matching what&#39;s stored by Salesforce on User records</description>
    <masterLabel>Time Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TimeEntryDataService.cls
public with sharing class TimeEntryDataService {

    /**
     * The Contact ID for the contact serviced by this instance
     */
    private Id contactId;

    /**
     * Map of cached service instances by Contact ID
     */
    private static Map<Id, TimeEntryDataService> instanceMap =
            new Map<Id, TimeEntryDataService>();

    public TimeEntryDataService(Id contactId) {
        this.contactId = contactId;
    }

    public static TimeEntryDataService getInstance(Id contactId) {

        // Add a new instance to the map
        if (!instanceMap.containsKey(contactId)) {
            instanceMap.put(contactId, new TimeEntryDataService(contactId));
        }

        // Return the instance
        return instanceMap.get(contactId);
    }

    public List<TimeEntry__c> getUnverifiedTimeEntries() {
        return [
            SELECT
                EndTime__c,
                EndTimeZoneSidKey__c,
                HasVerifiedEndTimeZone__c,
                HasVerifiedStartTimeZone__c,
                StartTime__c,
                StartTimeZoneSidKey__c,
                Id
            FROM TimeEntry__c
            WHERE
                (
                    HasVerifiedStartTimeZone__c = FALSE OR
                    HasVerifiedEndTimeZone__c = FALSE
                ) AND
                Contact__c = :this.contactId
        ];
    }

    public void verifyTimeZone(String timeZoneSidKey) {
        update TimeEntryUtil.verifyTimeZone(
                this.getUnverifiedTimeEntries(), timeZoneSidKey);
    }
}