src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>EndTIme__c</fullName>
        <label>End TIme</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/EndTimeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>EndTimeZoneSidKey__c</fullName>
    <description>The time zone in which the End Time was entered</description>
    <inlineHelpText>The time zone in which the End Time was entered</inlineHelpText>
    <label>End Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZoneSidKey</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/HasVerifiedEndTimeZone__c.field-meta.xml
<CustomField>
    <fullName>HasVerifiedEndTimeZone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the End Time Zone has been verified with the source of truth for the user&#39;s time zone</description>
    <inlineHelpText>Whether the End Time Zone has been verified with the source of truth for the user&#39;s time zone</inlineHelpText>
    <label>Verified End Time Zone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/HasVerifiedStartTimeZone__c.field-meta.xml
<CustomField>
    <fullName>HasVerifiedStartTimeZone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the Start Time Zone has been verified with the source of truth for the user&#39;s time zone</description>
    <inlineHelpText>Whether the Start Time Zone has been verified with the source of truth for the user&#39;s time zone</inlineHelpText>
    <label>Verified Start Time Zone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTimeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>StartTimeZoneSidKey__c</fullName>
    <description>The time zone in which the Start Time was entered</description>
    <inlineHelpText>The time zone in which the Start Time was entered</inlineHelpText>
    <label>Start Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TimeZoneSidKey</valueSetName>
    </valueSet>
</CustomField>

src/globalValueSets/TimeZoneSidKey.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Africa/Algiers</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Cairo</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Casablanca</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Johannesburg</fullName>
    </customValue>
    <customValue>
        <fullName>Africa/Nairobi</fullName>
    </customValue>
    <customValue>
        <fullName>America/Adak</fullName>
    </customValue>
    <customValue>
        <fullName>America/Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>America/Argentina/Buenos_Aires</fullName>
    </customValue>
    <customValue>
        <fullName>America/Bogota</fullName>
    </customValue>
    <customValue>
        <fullName>America/Caracas</fullName>
    </customValue>
    <customValue>
        <fullName>America/Chicago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Denver</fullName>
    </customValue>
    <customValue>
        <fullName>America/El_Salvador</fullName>
    </customValue>
    <customValue>
        <fullName>America/Halifax</fullName>
    </customValue>
    <customValue>
        <fullName>America/Indiana/Indianapolis</fullName>
    </customValue>
    <customValue>
        <fullName>America/Lima</fullName>
    </customValue>
    <customValue>
        <fullName>America/Los_Angeles</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mazatlan</fullName>
    </customValue>
    <customValue>
        <fullName>America/Mexico_City</fullName>
    </customValue>
    <customValue>
        <fullName>America/New_York</fullName>
        <default>true</default>
        <label>America/New_York</label>
    </customValue>
    <customValue>
        <fullName>America/Panama</fullName>
    </customValue>
    <customValue>
        <fullName>America/Phoenix</fullName>
    </customValue>
    <customValue>
        <fullName>America/Puerto_Rico</fullName>
    </customValue>
    <customValue>
        <fullName>America/Santiago</fullName>
    </customValue>
    <customValue>
        <fullName>America/Sao_Paulo</fullName>
    </customValue>
    <customValue>
        <fullName>America/Scoresbysund</fullName>
    </customValue>
    <customValue>
        <fullName>America/St_Johns</fullName>
    </customValue>
    <customValue>
        <fullName>America/Tijuana</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baghdad</fullName>
    </customValue>
    <customValue>
        <fullName>Asia/Baku</fullName>
    </customValue>
    <description>Time zone values matching what&apos;s stored by Salesforce on User records</description>
    <masterLabel>Time Zone</masterLabel>
</GlobalValueSet>

src/classes/TimeEntryUtil.cls
public class TimeEntryUtil {

    public static TimeEntry__c verifyEndTimeZone(
            TimeEntry__c record, String timeZoneSidKey) {
        return record.HasVerifiedEndTimeZone__c || record.EndTime__c == null
                ? record
                : verifyTimeZone(record, timeZoneSidKey,
                        TimeEntry__c.EndTime__c,
                        TimeEntry__c.EndTimeZoneSidKey__c,
                        TimeEntry__c.HasVerifiedEndTimeZone__c);
    }

    public static TimeEntry__c verifyStartTimeZone(
            TimeEntry__c record, String timeZoneSidKey) {
        return record.HasVerifiedStartTimeZone__c || record.StartTime__c == null
                ? record
                : verifyTimeZone(record, timeZoneSidKey,
                        TimeEntry__c.StartTime__c,
                        TimeEntry__c.StartTimeZoneSidKey__c,
                        TimeEntry__c.HasVerifiedStartTimeZone__c);
    }

    public static List<TimeEntry__c> verifyTimeZone(
            List<TimeEntry__c> records, String timeZoneSidKey) {

        // Initialize the list of verified records
        List<TimeEntry__c> verified = new List<TimeEntry__c>();

        // Verify any unverified time zones
        for (TimeEntry__c eachRecord : records) {

            // Start Time Zone
            eachRecord = verifyStartTimeZone(eachRecord, timeZoneSidKey);

            // End Time Zone
            eachRecord = verifyEndTimeZone(eachRecord, timeZoneSidKey); 

            // Add the record to the list of verified records
            verified.add(eachRecord);
        }

        // Return the updated records
        return verified;
    }

    public static TimeEntry__c verifyTimeZone(
            TimeEntry__c record,
            String timeZoneSidKey,
            Schema.SObjectField timeField,
            Schema.SObjectField timeZoneField,
            Schema.SObjectField verifiedField) {

        // Update the time and time zone if the assumed time zone differs
        // from the real, given time zone
        if (!timeZoneSidKey.equals(record.get(timeZoneField))) {

            // Calculate the new time that is expected to be correct
            // based on the given time zone
            TimeZone oldTimeZone =
                    TimeZone.getTimeZone((String)record.get(timeZoneField));
            
            TimeZone newTimeZone =
                    TimeZone.getTimeZone(timeZoneSidKey);
            
            Datetime oldTime = (Datetime)record.get(timeField);
            
            Datetime newTime =
                    DatetimeUtil.adjust(oldTime, newTimeZone, oldTimeZone);

            // Update the record with the new time and time zone
            record.put(timeField, newTime);
            record.put(timeZoneField, timeZoneSidKey);
        }

        // Mark the time as verified
        record.put(verifiedField, true);

        // Return the verified record
        return record;
    }
}