src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlice__c/TimeSlice__c.object-meta.xml
<CustomObject>
    <label>Time Slice</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Time Slice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlice__c/fields/TimeEntry__c.field-meta.xml
<CustomField>
    <fullName>TimeEntry__c</fullName>
    <label>Time Entry</label>
    <referenceTo>TimeEntry__c</referenceTo>
    <relationshipLabel>Time Slices</relationshipLabel>
    <relationshipName>TimeSlices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/classes/SlashclockUtilTest.cls
@isTest
private class SlashclockUtilTest {

    @isTest
    private static void emcee20170703SevenDayReportItems() {

        // Given
        String userId = 'em';
        String teamId = 'cee';

        SlashclockService clock = SlashclockService.getInstance(userId, teamId);

        DateTime startTime = DateTime.newInstanceGmt(2017, 7, 3, 0, 0, 0);
        DateTime endTime = DateTime.newInstanceGmt(2017, 7, 10, 0, 0, 0);

        List<TimeEntry__c> entries = clock.getTimeEntries(startTime, endTime);

        System.assertEquals(2, entries.size());
        
        System.assertEquals(
                DateTime.newInstanceGmt(2017, 7, 4, 8, 0, 0).format(),
                entries[0].StartTime__c.format());
        System.assertEquals(0, entries[0].TimeSlices__r.size());

        System.assertEquals(
                DateTime.newInstanceGmt(2017, 7, 5, 8, 0, 0).format(),
                entries[1].StartTime__c.format());
        System.assertEquals(1, entries[1].TimeSlices__r.size());

        // When
        Test.startTest();

        List<SlashclockReportItem> items = SlashclockUtil.newDailyReportItems(
                startTime, endTime, 'GMT', entries, 7);

        // Then
        Test.stopTest();

        System.assertEquals(7, items.size(), 'number of report items');

        System.assertEquals('Mon 0h', items[0].format());
        System.assertEquals('Tue 9h', items[1].format());
        System.assertEquals('Wed 9.5h (1.5h apex)', items[2].format());
        System.assertEquals('Thu 0h', items[3].format());
        System.assertEquals('Fri 0h', items[4].format());
        System.assertEquals('Sat 0h', items[5].format());
        System.assertEquals('Sun 0h', items[6].format());
    }

    @testSetup
    private static void setup() {
        TestService.getInstance().setup();
    }
}