src/objects/TimeEntry__c.object
<CustomObject>
    <fields>
        <fullName>SlackTeamId__c</fullName>
        <label>Slack Team ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SlackUserId__c</fullName>
        <label>Slack User ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{0000000000}</displayFormat>
        <label>Time Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlashclockService.cls
public with sharing class SlashclockService {

    public static final String ALREADY_CLOCKED_IN_ERROR =
            'Uh, you already clocked in earlier.';

    /**
     * Slack Team ID
     */
    private String teamId;
    
    /**
     * Slack User ID
     */
    private String userId;

    public SlashclockService(String userId, String teamId) {
        this.userId = userId;
        this.teamId = teamId;        
    }

    /**
     * @param startTime
     *            The time at which the user clocked in
     *
     * @return newly created, open time entry
     */
    public TimeEntry__c clockIn(DateTime startTime) {

        // Look for existing open entries
        if (this.getOpenTimeEntries().size() > 0) {
            throw new SlashclockException(ALREADY_CLOCKED_IN_ERROR);
        }

        // Construct the time entry
        TimeEntry__c entry = new TimeEntry__c(
                StartTime__c = startTime,
                SlackUserId__c = this.userId,
                SlackTeamId__c = this.teamId);

        // Insert and return the time entry
        insert entry;
        return entry;
    }

    /**
     * @return all open time entries for the user in context
     */
    public List<TimeEntry__c> getOpenTimeEntries() {
        return [
            SELECT Id
            FROM TimeEntry__c
            WHERE SlackUserId__c = :this.userId
                AND SlackTeamId__c = :this.teamId
        ];
    }

    public static SlashclockService getInstance(String userId, String teamId) {
        return new SlashclockService(userId, teamId);
    }
}