force-app/main/default/objects/TimeSlice__c/TimeSlice__c.object-meta.xml
<CustomObject>
    <label>Time Slice</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Time Slice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlice__c/fields/NumberOfMinutes__c.field-meta.xml
<CustomField>
    <fullName>NumberOfMinutes__c</fullName>
    <label>Num Minutes</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeSlice__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/classes/SlashclockReportSlice.cls
public with sharing class SlashclockReportSlice {

    private Time2 duration;
    private String tag;

    public SlashclockReportSlice(Time2 duration, String tag) {
        this.duration = duration;
        this.tag = tag;
    }

    public String format() {
        return this.duration.formatH() + ' ' + this.tag;
    }

    public Time2 getDuration() {
        return this.duration;
    }

    public String getTag() {
        return this.tag;
    }

    public void increase(Time2 increment) {
        this.duration = this.duration.add(increment);
    }

    public static SlashclockReportSlice newInstance(TimeSlice__c record) {
        Integer minute = record.NumberOfMinutes__c.intValue();
        Time2 duration = Time2.newInstance(0, 0, minute, 0, 0);
        return new SlashclockReportSlice(duration, record.Tag__c);
    }
}